// <auto-generated />
using Larder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Larder.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240710153745_RecipeModelAndSeedData")]
    partial class RecipeModelAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Larder.Models.Ingredient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = "c108ae4e-c4a7-468b-891c-d2b69a849d1c",
                            Name = "Butter"
                        },
                        new
                        {
                            Id = "c22acee2-d2df-4e1e-854b-83e292778cc6",
                            Name = "Water"
                        },
                        new
                        {
                            Id = "f7845238-0ae4-4eda-b6bc-da98b6872c54",
                            Name = "Rice Roni Chicken Lower Sodium box"
                        });
                });

            modelBuilder.Entity("Larder.Models.Recipe", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = "461de933-f154-4f57-ad73-d57f6eaa9e3a",
                            Name = "Rice Roni Low Sodium Chicken Rice"
                        });
                });

            modelBuilder.Entity("Larder.Models.RecipeIngredient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("IngredientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UnitId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = "9b1a2d2f-4bb6-497e-9ebd-06dd4623d394",
                            Amount = 1.0,
                            IngredientId = "c108ae4e-c4a7-468b-891c-d2b69a849d1c",
                            RecipeId = "461de933-f154-4f57-ad73-d57f6eaa9e3a",
                            UnitId = "292e8e1a-8873-42c6-ba73-5a48f63ba8f8"
                        },
                        new
                        {
                            Id = "18fdedeb-9883-45ad-a94e-625176cfb8f1",
                            Amount = 2.5,
                            IngredientId = "c22acee2-d2df-4e1e-854b-83e292778cc6",
                            RecipeId = "461de933-f154-4f57-ad73-d57f6eaa9e3a",
                            UnitId = "a178a0ec-839d-4562-8131-0b0a40c1119e"
                        },
                        new
                        {
                            Id = "1c1956c1-5531-4959-bb46-751af6e9bcd3",
                            Amount = 1.0,
                            IngredientId = "f7845238-0ae4-4eda-b6bc-da98b6872c54",
                            RecipeId = "461de933-f154-4f57-ad73-d57f6eaa9e3a",
                            UnitId = "1f0cc34c-c4ed-4cfd-b08c-5630ed2ddd71"
                        });
                });

            modelBuilder.Entity("Larder.Models.Unit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = "bf04f43e-d84a-4006-a05e-f853f8fde955",
                            Name = "Liters",
                            Type = 1
                        },
                        new
                        {
                            Id = "4325eed7-b74b-43ea-bacd-b6fc2e69ab1c",
                            Name = "Pounds",
                            Type = 2
                        },
                        new
                        {
                            Id = "997dbfa1-3414-4a8f-a8cb-8d115c950c63",
                            Name = "Grams",
                            Type = 0
                        },
                        new
                        {
                            Id = "c2ac8bc5-36e2-4bc5-8d92-a9b640d42de4",
                            Name = "Milliliters",
                            Type = 1
                        },
                        new
                        {
                            Id = "292e8e1a-8873-42c6-ba73-5a48f63ba8f8",
                            Name = "Tablespoons",
                            Type = 1
                        },
                        new
                        {
                            Id = "a178a0ec-839d-4562-8131-0b0a40c1119e",
                            Name = "Cups",
                            Type = 1
                        },
                        new
                        {
                            Id = "1f0cc34c-c4ed-4cfd-b08c-5630ed2ddd71",
                            Name = "Quantity",
                            Type = 3
                        });
                });

            modelBuilder.Entity("Larder.Models.RecipeIngredient", b =>
                {
                    b.HasOne("Larder.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Larder.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Larder.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Larder.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
