// <auto-generated />
using Larder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Larder.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240718152104_AddRecipeIngredientsToIngredient")]
    partial class AddRecipeIngredientsToIngredient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Larder.Models.Ingredient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = "17d5f1c2-0356-4ed1-9e4b-d9a834f6cfe9",
                            Name = "Butter",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = "4b9bdb39-97d2-4c34-87c5-8a47fbfc5657",
                            Name = "Water",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = "447e61e6-3040-471b-8205-75a721d56509",
                            Name = "Rice Roni Chicken Lower Sodium box",
                            Quantity = 0.0
                        });
                });

            modelBuilder.Entity("Larder.Models.Recipe", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = "9b0baed7-1e3f-4a48-9b9f-a117c984cee7",
                            Name = "Rice Roni Low Sodium Chicken Rice"
                        });
                });

            modelBuilder.Entity("Larder.Models.RecipeIngredient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("IngredientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UnitId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = "bef9504a-87ff-4de8-9a5f-4aa4dd749cd0",
                            Amount = 1.0,
                            IngredientId = "17d5f1c2-0356-4ed1-9e4b-d9a834f6cfe9",
                            RecipeId = "9b0baed7-1e3f-4a48-9b9f-a117c984cee7",
                            UnitId = "7fff43c6-7955-4bd9-880d-602b076e54f6"
                        },
                        new
                        {
                            Id = "fd3d1460-3f48-437e-b228-9af7ff1106fb",
                            Amount = 2.5,
                            IngredientId = "4b9bdb39-97d2-4c34-87c5-8a47fbfc5657",
                            RecipeId = "9b0baed7-1e3f-4a48-9b9f-a117c984cee7",
                            UnitId = "19694c4c-8415-41fc-b86d-12bb1bf17f6f"
                        },
                        new
                        {
                            Id = "a15cd4f1-feb5-4f0f-994a-2428a0570668",
                            Amount = 1.0,
                            IngredientId = "447e61e6-3040-471b-8205-75a721d56509",
                            RecipeId = "9b0baed7-1e3f-4a48-9b9f-a117c984cee7",
                            UnitId = "121e16f8-b546-4860-950a-2f112984f1a2"
                        });
                });

            modelBuilder.Entity("Larder.Models.Unit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = "feef8440-d56a-4d40-bb9d-760565dd108a",
                            Name = "Liters",
                            Type = 1
                        },
                        new
                        {
                            Id = "6fa124ca-be60-4ca3-8f2f-8c47289e5c61",
                            Name = "Pounds",
                            Type = 2
                        },
                        new
                        {
                            Id = "4d24c449-ad9a-4877-9c39-78816171e023",
                            Name = "Grams",
                            Type = 0
                        },
                        new
                        {
                            Id = "f2a2dcf5-01a0-4317-8338-50e0f13ca183",
                            Name = "Milliliters",
                            Type = 1
                        },
                        new
                        {
                            Id = "7fff43c6-7955-4bd9-880d-602b076e54f6",
                            Name = "Tablespoons",
                            Type = 1
                        },
                        new
                        {
                            Id = "19694c4c-8415-41fc-b86d-12bb1bf17f6f",
                            Name = "Cups",
                            Type = 1
                        },
                        new
                        {
                            Id = "121e16f8-b546-4860-950a-2f112984f1a2",
                            Name = "Quantity",
                            Type = 3
                        });
                });

            modelBuilder.Entity("Larder.Models.RecipeIngredient", b =>
                {
                    b.HasOne("Larder.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Larder.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Larder.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Larder.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("Larder.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
