// <auto-generated />
using Larder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Larder.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240707162105_AddUnitsSeedData")]
    partial class AddUnitsSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Larder.Models.Unit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = "4c3479a5-a562-4e64-8c9b-7e4c144e0015",
                            Name = "Liters"
                        },
                        new
                        {
                            Id = "2a9d9207-e9e8-4c4e-8931-e58111626070",
                            Name = "Pounds"
                        },
                        new
                        {
                            Id = "2c67b0ff-9d7e-4542-8b37-bb6382766014",
                            Name = "Grams"
                        },
                        new
                        {
                            Id = "10b3195c-6cd8-40b6-9e5d-ae9bf7b714f0",
                            Name = "Milliliters"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
