// <auto-generated />
using Larder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Larder.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240720141439_DropUnitIdNotNullConstraintOnRecipeIngredients")]
    partial class DropUnitIdNotNullConstraintOnRecipeIngredients
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Larder.Models.Ingredient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<string>("UnitId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = "3e2d8654-1750-4eed-b7a9-56ea0fd6526e",
                            Name = "Butter",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = "c92cbe37-ba53-4ba6-955c-a07af8c0bc5b",
                            Name = "Water",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = "8a851123-514d-4145-9ae3-bb4feef9de35",
                            Name = "Rice Roni Chicken Lower Sodium box",
                            Quantity = 0.0
                        });
                });

            modelBuilder.Entity("Larder.Models.Recipe", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = "b42c7e12-0d90-48a6-aae8-d7cc5fa8a946",
                            Name = "Rice Roni Low Sodium Chicken Rice"
                        });
                });

            modelBuilder.Entity("Larder.Models.RecipeIngredient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("IngredientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UnitId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = "a2d93f87-471c-47ec-b8cc-8f61cfdb90c1",
                            Amount = 1.0,
                            IngredientId = "3e2d8654-1750-4eed-b7a9-56ea0fd6526e",
                            RecipeId = "b42c7e12-0d90-48a6-aae8-d7cc5fa8a946",
                            UnitId = "0e39f9f1-0f06-49bc-be74-6a9635357dd2"
                        },
                        new
                        {
                            Id = "12ff74d3-fce4-4b8e-ab7a-2931ab710bbe",
                            Amount = 2.5,
                            IngredientId = "c92cbe37-ba53-4ba6-955c-a07af8c0bc5b",
                            RecipeId = "b42c7e12-0d90-48a6-aae8-d7cc5fa8a946",
                            UnitId = "6e67f9ba-c94a-4c3f-94a0-14c48f8b19c0"
                        },
                        new
                        {
                            Id = "41aafa88-9008-41d7-b9b4-19879dc0b89a",
                            Amount = 1.0,
                            IngredientId = "8a851123-514d-4145-9ae3-bb4feef9de35",
                            RecipeId = "b42c7e12-0d90-48a6-aae8-d7cc5fa8a946"
                        });
                });

            modelBuilder.Entity("Larder.Models.Unit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = "40311b6e-2362-471a-83ec-186e62c96a98",
                            Name = "Liters",
                            Type = 1
                        },
                        new
                        {
                            Id = "e1188fd4-922a-4155-bb50-5445c08d7764",
                            Name = "Pounds",
                            Type = 2
                        },
                        new
                        {
                            Id = "9ec72596-961a-4469-9f2b-d0007c7ead00",
                            Name = "Grams",
                            Type = 0
                        },
                        new
                        {
                            Id = "47e0c7b0-9bed-42ab-9b4a-eedd291421dc",
                            Name = "Milliliters",
                            Type = 1
                        },
                        new
                        {
                            Id = "0e39f9f1-0f06-49bc-be74-6a9635357dd2",
                            Name = "Tablespoons",
                            Type = 1
                        },
                        new
                        {
                            Id = "6e67f9ba-c94a-4c3f-94a0-14c48f8b19c0",
                            Name = "Cups",
                            Type = 1
                        });
                });

            modelBuilder.Entity("Larder.Models.Ingredient", b =>
                {
                    b.HasOne("Larder.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Larder.Models.RecipeIngredient", b =>
                {
                    b.HasOne("Larder.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Larder.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Larder.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Larder.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("Larder.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
