// <auto-generated />
using Larder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Larder.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240709190345_AddTypeToUnits")]
    partial class AddTypeToUnits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Larder.Models.Unit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = "2462b142-60b1-4e76-95f9-91bdf255d2d8",
                            Name = "Liters",
                            Type = 1
                        },
                        new
                        {
                            Id = "31b3b97f-a331-4f36-bd7a-3a2c1a638c0e",
                            Name = "Pounds",
                            Type = 2
                        },
                        new
                        {
                            Id = "981124a0-14a4-4281-aac6-edbfad893073",
                            Name = "Grams",
                            Type = 0
                        },
                        new
                        {
                            Id = "d1865374-cba5-49c0-9310-5cf864adc9a0",
                            Name = "Milliliters",
                            Type = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
