// <auto-generated />
using Larder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Larder.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240718154530_AddUnitToIngredient")]
    partial class AddUnitToIngredient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Larder.Models.Ingredient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<string>("UnitId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = "1d1ce30f-6704-444c-939f-791a036022df",
                            Name = "Butter",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = "021e52c2-1bf9-45de-ac1e-7a1cdebde99f",
                            Name = "Water",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = "99be26f0-5587-4a6b-84eb-b2dbee74d6ca",
                            Name = "Rice Roni Chicken Lower Sodium box",
                            Quantity = 0.0
                        });
                });

            modelBuilder.Entity("Larder.Models.Recipe", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = "177052ad-f8a8-46b1-90c0-6eb980f65a89",
                            Name = "Rice Roni Low Sodium Chicken Rice"
                        });
                });

            modelBuilder.Entity("Larder.Models.RecipeIngredient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("IngredientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UnitId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = "2fc7c3c4-91b4-4286-baaf-32f68b21f450",
                            Amount = 1.0,
                            IngredientId = "1d1ce30f-6704-444c-939f-791a036022df",
                            RecipeId = "177052ad-f8a8-46b1-90c0-6eb980f65a89",
                            UnitId = "fbc59e6d-c07b-47e6-a64a-6aa6114e45f5"
                        },
                        new
                        {
                            Id = "604777b3-bf90-455f-b99e-5f23912926e4",
                            Amount = 2.5,
                            IngredientId = "021e52c2-1bf9-45de-ac1e-7a1cdebde99f",
                            RecipeId = "177052ad-f8a8-46b1-90c0-6eb980f65a89",
                            UnitId = "56e1a33c-9226-44b4-bfb0-310841c4da39"
                        },
                        new
                        {
                            Id = "ff01c81e-61ec-4f9e-8478-f7d14fe17328",
                            Amount = 1.0,
                            IngredientId = "99be26f0-5587-4a6b-84eb-b2dbee74d6ca",
                            RecipeId = "177052ad-f8a8-46b1-90c0-6eb980f65a89",
                            UnitId = "1da7ddf3-2068-43fc-8e15-ccf62418fa33"
                        });
                });

            modelBuilder.Entity("Larder.Models.Unit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = "6b92fee2-1a11-486c-84ea-70e2ea575430",
                            Name = "Liters",
                            Type = 1
                        },
                        new
                        {
                            Id = "707bde98-791e-498b-a0ed-ab620d33c907",
                            Name = "Pounds",
                            Type = 2
                        },
                        new
                        {
                            Id = "1d93c337-66a1-44dc-8c65-0007e3262081",
                            Name = "Grams",
                            Type = 0
                        },
                        new
                        {
                            Id = "dafeefec-b803-409f-86e8-76b8062a31bc",
                            Name = "Milliliters",
                            Type = 1
                        },
                        new
                        {
                            Id = "fbc59e6d-c07b-47e6-a64a-6aa6114e45f5",
                            Name = "Tablespoons",
                            Type = 1
                        },
                        new
                        {
                            Id = "56e1a33c-9226-44b4-bfb0-310841c4da39",
                            Name = "Cups",
                            Type = 1
                        },
                        new
                        {
                            Id = "1da7ddf3-2068-43fc-8e15-ccf62418fa33",
                            Name = "Quantity",
                            Type = 3
                        });
                });

            modelBuilder.Entity("Larder.Models.Ingredient", b =>
                {
                    b.HasOne("Larder.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Larder.Models.RecipeIngredient", b =>
                {
                    b.HasOne("Larder.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Larder.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Larder.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Larder.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("Larder.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
