// <auto-generated />
using Larder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Larder.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240806182540_SeedDataFollowingQuantitiesRefactor")]
    partial class SeedDataFollowingQuantitiesRefactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("IngredientRecipe", b =>
                {
                    b.Property<string>("IngredientsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipesId")
                        .HasColumnType("TEXT");

                    b.HasKey("IngredientsId", "RecipesId");

                    b.HasIndex("RecipesId");

                    b.ToTable("IngredientRecipe");
                });

            modelBuilder.Entity("Larder.Models.Item", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Larder.Models.Quantity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeIngredientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.HasIndex("RecipeIngredientId")
                        .IsUnique();

                    b.HasIndex("UnitId");

                    b.ToTable("Quantities");

                    b.HasData(
                        new
                        {
                            Id = "c0c130cf-46b8-4d29-b752-6f14abcc6f6e",
                            Amount = 1.0,
                            RecipeIngredientId = "f192906a-d0ee-4070-8637-8dbfc625e2c6",
                            UnitId = "80019b5f-2421-43f4-9dbc-34b9410175ba"
                        },
                        new
                        {
                            Id = "4f36bb33-5748-4b8c-b4b7-74d31ce1ab3b",
                            Amount = 2.5,
                            RecipeIngredientId = "3fafbcb2-36db-4c93-b258-a2076e492a5b",
                            UnitId = "981342be-e3c6-4d29-ae24-323751268ffa"
                        },
                        new
                        {
                            Id = "09cdc1e5-1a8d-4807-bb75-47a205358508",
                            Amount = 1.0,
                            RecipeIngredientId = "77c040d5-0721-4a70-a744-5930f6ec4e5a"
                        });
                });

            modelBuilder.Entity("Larder.Models.Recipe", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FoodId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ServingsProduced")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FoodId")
                        .IsUnique();

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = "39e0ae76-2028-4a64-b916-3c867d33cd6a",
                            FoodId = "e82cf4ef-de27-4047-93fb-9b646b18e429",
                            Name = "Rice Roni Low Sodium Chicken Rice",
                            ServingsProduced = 0
                        });
                });

            modelBuilder.Entity("Larder.Models.RecipeIngredient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("IngredientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = "f192906a-d0ee-4070-8637-8dbfc625e2c6",
                            IngredientId = "ba79b505-ef1c-4a3c-ac11-f238c96cf55a",
                            RecipeId = "39e0ae76-2028-4a64-b916-3c867d33cd6a"
                        },
                        new
                        {
                            Id = "3fafbcb2-36db-4c93-b258-a2076e492a5b",
                            IngredientId = "8c30b3bf-8d97-4698-a54e-65ba9ffb6874",
                            RecipeId = "39e0ae76-2028-4a64-b916-3c867d33cd6a"
                        },
                        new
                        {
                            Id = "77c040d5-0721-4a70-a744-5930f6ec4e5a",
                            IngredientId = "b8365ef1-1945-4b95-985f-bf7fdc0d8959",
                            RecipeId = "39e0ae76-2028-4a64-b916-3c867d33cd6a"
                        });
                });

            modelBuilder.Entity("Larder.Models.RecipeStep", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeSteps");
                });

            modelBuilder.Entity("Larder.Models.Unit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = "39f859ef-a613-4cbf-8150-436180e0ea9b",
                            Name = "Liters",
                            Type = 1
                        },
                        new
                        {
                            Id = "38117f39-1bc2-43a3-9433-fc566d1cf405",
                            Name = "Pounds",
                            Type = 2
                        },
                        new
                        {
                            Id = "548ba096-d9e3-4e00-9c39-e3bfaafc94f1",
                            Name = "Grams",
                            Type = 0
                        },
                        new
                        {
                            Id = "67afa4e1-6aed-496e-95cf-4f082af69907",
                            Name = "Milliliters",
                            Type = 1
                        },
                        new
                        {
                            Id = "80019b5f-2421-43f4-9dbc-34b9410175ba",
                            Name = "Tablespoons",
                            Type = 1
                        },
                        new
                        {
                            Id = "981342be-e3c6-4d29-ae24-323751268ffa",
                            Name = "Cups",
                            Type = 1
                        });
                });

            modelBuilder.Entity("Larder.Models.Food", b =>
                {
                    b.HasBaseType("Larder.Models.Item");

                    b.Property<double>("Calories")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("Food");

                    b.HasData(
                        new
                        {
                            Id = "e82cf4ef-de27-4047-93fb-9b646b18e429",
                            Name = "Chicken and rice",
                            Calories = 0.0
                        });
                });

            modelBuilder.Entity("Larder.Models.Ingredient", b =>
                {
                    b.HasBaseType("Larder.Models.Item");

                    b.HasDiscriminator().HasValue("Ingredient");

                    b.HasData(
                        new
                        {
                            Id = "ba79b505-ef1c-4a3c-ac11-f238c96cf55a",
                            Name = "Butter"
                        },
                        new
                        {
                            Id = "8c30b3bf-8d97-4698-a54e-65ba9ffb6874",
                            Name = "Water"
                        },
                        new
                        {
                            Id = "b8365ef1-1945-4b95-985f-bf7fdc0d8959",
                            Name = "Rice Roni Chicken Lower Sodium box"
                        });
                });

            modelBuilder.Entity("Larder.Models.Utensil", b =>
                {
                    b.HasBaseType("Larder.Models.Item");

                    b.HasDiscriminator().HasValue("Utensil");
                });

            modelBuilder.Entity("IngredientRecipe", b =>
                {
                    b.HasOne("Larder.Models.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Larder.Models.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Larder.Models.Quantity", b =>
                {
                    b.HasOne("Larder.Models.Item", "Item")
                        .WithOne("Quantity")
                        .HasForeignKey("Larder.Models.Quantity", "ItemId");

                    b.HasOne("Larder.Models.RecipeIngredient", "RecipeIngredient")
                        .WithOne("Quantity")
                        .HasForeignKey("Larder.Models.Quantity", "RecipeIngredientId");

                    b.HasOne("Larder.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.Navigation("Item");

                    b.Navigation("RecipeIngredient");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Larder.Models.Recipe", b =>
                {
                    b.HasOne("Larder.Models.Food", "Food")
                        .WithOne("Recipe")
                        .HasForeignKey("Larder.Models.Recipe", "FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("Larder.Models.RecipeIngredient", b =>
                {
                    b.HasOne("Larder.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Larder.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Larder.Models.RecipeStep", b =>
                {
                    b.HasOne("Larder.Models.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Larder.Models.Item", b =>
                {
                    b.Navigation("Quantity");
                });

            modelBuilder.Entity("Larder.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Larder.Models.RecipeIngredient", b =>
                {
                    b.Navigation("Quantity");
                });

            modelBuilder.Entity("Larder.Models.Food", b =>
                {
                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Larder.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
