// <auto-generated />
using Larder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Larder.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240718140638_AddQuantityToIngredients")]
    partial class AddQuantityToIngredients
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Larder.Models.Ingredient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = "82aa1800-9bce-4b0d-8d99-7e2e8fba005f",
                            Name = "Butter",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = "08b53ffa-124c-4da9-bbbc-d25981c43f06",
                            Name = "Water",
                            Quantity = 0.0
                        },
                        new
                        {
                            Id = "e2400176-19d8-488e-8633-1cf5be5abbb2",
                            Name = "Rice Roni Chicken Lower Sodium box",
                            Quantity = 0.0
                        });
                });

            modelBuilder.Entity("Larder.Models.Recipe", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = "3efc935a-0905-4e45-b6b1-b023e98f10b7",
                            Name = "Rice Roni Low Sodium Chicken Rice"
                        });
                });

            modelBuilder.Entity("Larder.Models.RecipeIngredient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("IngredientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UnitId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = "8ddf0f5d-80aa-4dbc-87d8-66e69c251ff0",
                            Amount = 1.0,
                            IngredientId = "82aa1800-9bce-4b0d-8d99-7e2e8fba005f",
                            RecipeId = "3efc935a-0905-4e45-b6b1-b023e98f10b7",
                            UnitId = "93517d52-14d1-4599-ac9e-7ab0d8f1a33f"
                        },
                        new
                        {
                            Id = "7ba449eb-8c4d-49d3-a500-2437639db4c0",
                            Amount = 2.5,
                            IngredientId = "08b53ffa-124c-4da9-bbbc-d25981c43f06",
                            RecipeId = "3efc935a-0905-4e45-b6b1-b023e98f10b7",
                            UnitId = "04f730b7-e48a-4c69-b4b0-6fd55a560614"
                        },
                        new
                        {
                            Id = "2f3deccf-945d-4b15-858d-632a030866b8",
                            Amount = 1.0,
                            IngredientId = "e2400176-19d8-488e-8633-1cf5be5abbb2",
                            RecipeId = "3efc935a-0905-4e45-b6b1-b023e98f10b7",
                            UnitId = "958910f9-a7cd-45ce-b213-b223c944322c"
                        });
                });

            modelBuilder.Entity("Larder.Models.Unit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = "ec7c77e7-e6ce-4971-a054-ebbb0f8b37c8",
                            Name = "Liters",
                            Type = 1
                        },
                        new
                        {
                            Id = "c812ebf2-d336-4914-95fe-98acdc1b8c44",
                            Name = "Pounds",
                            Type = 2
                        },
                        new
                        {
                            Id = "11a6951e-c0db-4326-9aea-106f2491b9fb",
                            Name = "Grams",
                            Type = 0
                        },
                        new
                        {
                            Id = "fc29c213-6a7b-4900-b2b9-a7f99028a3c9",
                            Name = "Milliliters",
                            Type = 1
                        },
                        new
                        {
                            Id = "93517d52-14d1-4599-ac9e-7ab0d8f1a33f",
                            Name = "Tablespoons",
                            Type = 1
                        },
                        new
                        {
                            Id = "04f730b7-e48a-4c69-b4b0-6fd55a560614",
                            Name = "Cups",
                            Type = 1
                        },
                        new
                        {
                            Id = "958910f9-a7cd-45ce-b213-b223c944322c",
                            Name = "Quantity",
                            Type = 3
                        });
                });

            modelBuilder.Entity("Larder.Models.RecipeIngredient", b =>
                {
                    b.HasOne("Larder.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Larder.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Larder.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Larder.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
