name: my-github-action

on: [push]

jobs:
  build-and-deploy-react-client:
    environment: development
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install
      - name: Build React app
        run: npm run build
      - name: SCP bundle to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          source: "./client/dist"
          target: /var/www/larder_client

  build-test-and-deploy-webapi:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: '8.0.x'
      - name: Run tests
        run: dotnet test WebApi.Tests
      - name: Publish self-contained executable
        run: dotnet publish WebApi -r linux-arm64 --self-contained true
      - name: SCP dotnet executable to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          source: "./WebApi/bin/Release/net8.0/linux-arm64/publish"
          target: ${{ secrets.WEBAPI_DEPLOY_DIRECTORY }}
