name: my-github-action

on: [push]

jobs:
  build-and-deploy-react-client:
    environment: development
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install
      - name: Build React app
        run: npm run build
      - name: SCP bundle to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          source: "./client/build"
          target: /var/www/larder_client

  # run-tests:
  #   environment: development
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v4
  #       with:
  #           dotnet-version: '8.0.x'

  #     - name: Run tests
  #       run: dotnet test WebApi.Tests

  #     - name: Test SSHing to VM
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         key: ${{ secrets.PRIVATE_SSH_KEY }}
  #         script: echo 'hello world'
